In [17]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [18]:
df = pd.read_csv("../data/raw/Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
df.info()

df.describe()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [20]:
df["Age"] = df["Age"].fillna(df["Age"].median())

df["Embarked"] = df["Embarked"].fillna(
    df["Embarked"].mode()[0]
)

df["Fare"] = df["Fare"].fillna(
    df["Fare"].median()
)

In [21]:
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

In [22]:
df["IsAlone"] = np.where(
    df["FamilySize"] == 1,
    1,
    0
)

In [23]:
df["Title"] = df["Name"].str.extract(
    r"([A-Za-z]+)\.",
    expand=False
)

In [24]:
df.drop(
    ["PassengerId", "Name", "Ticket", "Cabin"],
    axis=1,
    inplace=True
)

In [25]:
le = LabelEncoder()

df["Sex"] = le.fit_transform(df["Sex"])

In [26]:
df = pd.get_dummies(
    df,
    columns=["Embarked", "Title"],
    drop_first=True
)

In [27]:
scaler = StandardScaler()

df[["Age", "Fare"]] = scaler.fit_transform(
    df[["Age", "Fare"]]
)

In [28]:
minmax = MinMaxScaler()

df[["FamilySize"]] = minmax.fit_transform(
    df[["FamilySize"]]
)

In [29]:
df.to_csv(
    "../data/processed/Titanic_Preprocessed.csv",
    index=False
)

In [30]:
df.head()

df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Survived        891 non-null    int64
 1   Pclass          891 non-null    int64
 2   Sex             891 non-null    int64
 3   Age             891 non-null    float64
 4   SibSp           891 non-null    int64
 5   Parch           891 non-null    int64
 6   Fare            891 non-null    float64
 7   FamilySize      891 non-null    float64
 8   IsAlone         891 non-null    int64
 9   Embarked_Q      891 non-null    bool
 10  Embarked_S      891 non-null    bool
 11  Title_Col       891 non-null    bool
 12  Title_Countess  891 non-null    bool
 13  Title_Don       891 non-null    bool
 14  Title_Dr        891 non-null    bool
 15  Title_Jonkheer  891 non-null    bool
 16  Title_Lady      891 non-null    bool
 17  Title_Major     891 non-null    bool
 18  Title_Master    891 non-null    bool
 19  Title_Miss      891 non-null    bool
 20  Title_Mlle      891 non-null    bool
 21  Title_Mme       891 non-null    bool
 22  Title_Mr        891 non-null    bool
 23  Title_Mrs       891 non-null    bool
 24  Title_Ms        891 non-null    bool
 25  Title_Rev       891 non-null    bool
 26  Title_Sir       891 non-null    bool
dtypes: bool(18), float64(3), int64(6)
memory usage: 78.4 KB

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,FamilySize,IsAlone
count,891.000000,891.000000,891.000000,8.910000e+02,891.000000,891.000000,8.910000e+02,891.000000,891.000000
mean,0.383838,2.308642,0.647587,2.272780e-16,0.523008,0.381594,3.987333e-18,0.090460,0.602694
std,0.486592,0.836071,0.477990,1.000562e+00,1.102743,0.806057,1.000562e+00,0.161346,0.489615
min,0.000000,1.000000,0.000000,-2.224156e+00,0.000000,0.000000,-6.484217e-01,0.000000,0.000000
25%,0.000000,2.000000,0.000000,-5.657365e-01,0.000000,0.000000,-4.891482e-01,0.000000,0.000000
50%,0.000000,3.000000,1.000000,-1.046374e-01,0.000000,0.000000,-3.573909e-01,0.000000,1.000000
75%,1.000000,3.000000,1.000000,4.333115e-01,1.000000,0.000000,-2.424635e-02,0.100000,1.000000
max,1.000000,3.000000,1.000000,3.891554e+00,8.000000,6.000000,9.667167e+00,1.000000,1.000000